# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DefaultApi")

api.instance <- DefaultApi$new()

test_that("AddNextflowEventNextflowEventsPost", {
  # tests for AddNextflowEventNextflowEventsPost
  # base path: https://cmgd-telemetry-whnnxetv4q-uc.a.run.app
  # Add Nextflow Event
  # Events from running Nextflow pipelines when using -with-weblog.  See [the Nextflow documentation](https://www.nextflow.io/docs/latest/tracing.html#weblog-via-http).
  # @param nf.model NFModel 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateSampleMetadataSamplesPost", {
  # tests for CreateSampleMetadataSamplesPost
  # base path: https://cmgd-telemetry-whnnxetv4q-uc.a.run.app
  # Create Sample
  # @param sample Sample 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateStudyMetadataStudiesPost", {
  # tests for CreateStudyMetadataStudiesPost
  # base path: https://cmgd-telemetry-whnnxetv4q-uc.a.run.app
  # Create Study
  # @param study Study 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteStudyMetadataStudiesUuidDelete", {
  # tests for DeleteStudyMetadataStudiesUuidDelete
  # base path: https://cmgd-telemetry-whnnxetv4q-uc.a.run.app
  # Delete Study
  # @param uuid character 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("FilesChangeFilesChangesPost", {
  # tests for FilesChangeFilesChangesPost
  # base path: https://cmgd-telemetry-whnnxetv4q-uc.a.run.app
  # Files Change
  # Track all changes in cloud storage
  # @param body object 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GenerateDownloadSignedUrlV4FilesSignedGet", {
  # tests for GenerateDownloadSignedUrlV4FilesSignedGet
  # base path: https://cmgd-telemetry-whnnxetv4q-uc.a.run.app
  # Generate Download Signed Url V4
  # Generates a v4 signed URL for downloading a blob.  Note that this method requires a service account key file. You can not use this if you are using Application Default Credentials from Google Compute Engine or from the Google Cloud SDK.
  # @param name character 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetNextflowEventNextflowEventsIdGet", {
  # tests for GetNextflowEventNextflowEventsIdGet
  # base path: https://cmgd-telemetry-whnnxetv4q-uc.a.run.app
  # Get Nextflow Event
  # @param id character 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetSamplesMetadataSamplesGet", {
  # tests for GetSamplesMetadataSamplesGet
  # base path: https://cmgd-telemetry-whnnxetv4q-uc.a.run.app
  # Get Samples
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetStudiesMetadataStudiesGet", {
  # tests for GetStudiesMetadataStudiesGet
  # base path: https://cmgd-telemetry-whnnxetv4q-uc.a.run.app
  # Get Studies
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetUuidFromStringMetadataUuidGet", {
  # tests for GetUuidFromStringMetadataUuidGet
  # base path: https://cmgd-telemetry-whnnxetv4q-uc.a.run.app
  # Get Uuid From String
  # @param string character 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListFileEventsFilesChangesGet", {
  # tests for ListFileEventsFilesChangesGet
  # base path: https://cmgd-telemetry-whnnxetv4q-uc.a.run.app
  # List File Events
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @param start.date character  (optional)
  # @param end.date character  (optional)
  # @param filename.regex character  (optional)
  # @return [StorageEventCollection]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListNextflowEventsNextflowEventsGet", {
  # tests for ListNextflowEventsNextflowEventsGet
  # base path: https://cmgd-telemetry-whnnxetv4q-uc.a.run.app
  # List Nextflow Events
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @return [NFCollection]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SamplesForStudyMetadataStudiesUuidSamplesGet", {
  # tests for SamplesForStudyMetadataStudiesUuidSamplesGet
  # base path: https://cmgd-telemetry-whnnxetv4q-uc.a.run.app
  # Samples For Study
  # @param uuid character 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SamplesJsonMetadataSamplesjsonGet", {
  # tests for SamplesJsonMetadataSamplesjsonGet
  # base path: https://cmgd-telemetry-whnnxetv4q-uc.a.run.app
  # Samples Json
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

